### ISSUE TITLE
Support list in lua environment

### ISSUE THREAD

**Issue by yuukilla** [javiorfo/nvim-ship#1]
Sometimes its needed to provide bunch of headers in multiple places and to not all the time write them manually would be fine if existed support for lists in environment.
for example
```lua
return {
	host = "localhost",
	list_headers = {
		"some-example-header-1",
		"some-example-header-1",
	}
}
```

```
~[BASE]~
...

~[HEADERS]~
{{list_headers}}
```

**Comment by javiorfo** [comment]
Hi, yuukilla
Altough your proposition is interesting, the idea is to keep the "tags" (the left keys of ship archive) visible to help comprehension. Only values will be configurable in lua files.

You can use comments (`# this is a comment`) in ship files if you want to change values continuosly. I personally use this technique all the time.

```
~[BASE]~
url https://some.com
# url https://some.com

~[HEADERS]~
some-example-header-1 some_value
# some-example-header-1 some_value
some-example-header-2 some_value
```

Thanks for your comment!
Have a nice day!
