### ISSUE TITLE
Auto completion stopped working after 2090fbf

### ISSUE THREAD

**Issue by rodhash** [javiorfo/nvim-ship#2]
Hi .. great project!

In latest commit my auto completion doesn't work.

Tried forcing that to True and also tried leaving default config like this:

```lua
  {
    'javiorfo/nvim-ship',
    lazy = true,
    ft = 'ship',
    dependencies = {
      'javiorfo/nvim-spinetta',
      'javiorfo/nvim-popcorn',
      'hrsh7th/nvim-cmp' -- nvim-cmp is optional
    },
    opts = {}
  },
```

Switch back to previous commit `550b9bdcbe47e0276c23f3658cd2063bb8823d19` makes completion work again .. now it's working just fine

Am I missing any new config (even tho docs say auto completion is enabled by default)?

Thanks

**Comment by javiorfo** [comment]
Hello @rodhash 

I have pushed a new commit. There was a bug in the config.
You can pull it and the problem is solved.

Thanks for let me know about it.
