### ISSUE TITLE
Expose popcorn as variable?

### ISSUE THREAD

**Issue by rodhash** [javiorfo/nvim-ship#3]
Can this "border" value be exposed to us so we choose the border style? Checking the popcorn docs I really enjoyed "double_simple_border"

https://github.com/javiorfo/nvim-ship/blob/02496201380d806772f176d6ed074ec0e90409d4/lua/ship/core.lua#L139

I'm not too skilled with lua but I can try raising a PR if you want.

Thanks

**Comment by javiorfo** [comment]
Hi, @rodhash 

Now the you can choose the popup border style in response configs:

```lua
response = {
  show_headers = 'all',
  window_type = 'h',
  border_type = require'popcorn.borders'.double_border, -- Only applied for 'p' window_type
  size = 20,
  redraw = true
},
```

**Comment by rodhash** [comment]
> Hi, @rodhash
> 
> Now the you can choose the popup border style in response configs:
> 
> ```lua
> response = {
>   show_headers = 'all',
>   window_type = 'h',
>   border_type = require'popcorn.borders'.double_border, -- Only applied for 'p' window_type
>   size = 20,
>   redraw = true
> },
> ```

Thanks for the prompt feedback .. latest commit working fine, awesome
