### ISSUE TITLE
Completion adding an extra ":" char

### ISSUE THREAD

**Issue by rodhash** [javiorfo/nvim-ship#5]
When using the completion it adds an extra ":" char between authorization and Bearer

```
~[HEADERS]~
content-type application/json
authorization: Bearer 
```

In the end it still works but I noticed it messes a bit when I need to handle the token in the backend.. also no other completion seem to add this extra ":", apparently this happens only with "authorization" completion

**Comment by javiorfo** [comment]
Hello,
You were right. I've just uploaded the fix for this

**Comment by rodhash** [comment]
> Hello, You were right. I've just uploaded the fix for this

Thank you
